from models.vae import VariationalAutoEncoder
from models.variational_auto_encoder import VariationalAutoEncoder \
    as OriginalVariationalAutoEncoder
from models.iw_vae import ImportanceWeightedVariationalAutoEncoder
from models.simple_neural_network import SimpleNeuralNetwork
from models.gmm_vae import GaussianMixtureVariationalAutoEncoder
from models.cvae import ClusterVariationalAutoEncoder
